using System.Collections.Generic;

namespace IllusionMods.KoikatuModdingTools
{
    internal static class Constants
    {
        internal const string ModsPath = @"Assets\Mods";
        internal const string ExamplesPath = @"Assets\Examples";
        internal const string ScriptsPath = @"Assets\Scripts";
        internal const string ShadersPath = @"Assets\Shaders";
        internal const string SB3UtilityScriptPath = @"Tools\SB3UGS\SB3UtilityScript.exe";
        internal const string BuildPath = @"Build\abdata";
        internal const string ShaderABPath = @"Assets\kk_shaders.unity3d";

        internal static readonly HashSet<string> GameNameList = new HashSet<string> { "koikatsu", "koikatu", "コイカツ" };
        internal static readonly Dictionary<string, string> ShaderABs = new Dictionary<string, string>
        {
            { "Custom/CustomUnlit-Outline",  ShaderABPath },
            { "Custom/Blend/Zero_Subtractive",  ShaderABPath },
            { "Custom/Blend/Additive",  ShaderABPath },
            { "Custom/Silhouette", ShaderABPath },
            { "CustomUnlit/Transparent DoubleSide",  ShaderABPath },
            { "Shader Forge/create_body", ShaderABPath },
            { "Shader Forge/create_eye", ShaderABPath },
            { "Shader Forge/create_eyewhite", ShaderABPath },
            { "Shader Forge/create_hair", ShaderABPath },
            { "Shader Forge/create_head", ShaderABPath },
            { "Shader Forge/create_topN", ShaderABPath },
            { "Shader Forge/main_alpha", ShaderABPath },
            { "Shader Forge/main_color", ShaderABPath },
            { "Shader Forge/main_emblem", ShaderABPath },
            { "Shader Forge/main_emblem_clothes", ShaderABPath },
            { "Shader Forge/main_hair", ShaderABPath },
            { "Shader Forge/main_hair_front", ShaderABPath },
            { "Shader Forge/main_hair_low", ShaderABPath },
            { "Shader Forge/main_item", ShaderABPath },
            { "Shader Forge/main_item_ditherd", ShaderABPath },
            { "Shader Forge/main_item_emission", ShaderABPath },
            { "Shader Forge/main_item_low", ShaderABPath },
            { "Shader Forge/main_item_studio", ShaderABPath },
            { "Shader Forge/main_item_studio_add", ShaderABPath },
            { "Shader Forge/main_item_studio_alpha", ShaderABPath },
            { "Shader Forge/main_opaque", ShaderABPath },
            { "Shader Forge/main_opaque2", ShaderABPath },
            { "Shader Forge/main_skin", ShaderABPath },
            { "Shader Forge/main_skin_low", ShaderABPath },
            { "Shader Forge/main_StandardMDK_studio",ShaderABPath },
            { "Shader Forge/main_opaque_low", ShaderABPath },
            { "Shader Forge/main_opaque_low2", ShaderABPath },
            { "Shader Forge/main_texture", ShaderABPath },
            { "Shader Forge/main_texture_studio", ShaderABPath },
            { "Shader Forge/mnpb", ShaderABPath },
            { "Shader Forge/shadowcast", ShaderABPath },
            { "Shader Forge/toon_eye_lod0", ShaderABPath },
            { "Shader Forge/toon_eyew_lod0", ShaderABPath },
            { "Shader Forge/toon_glasses_lod0", ShaderABPath },
            { "Shader Forge/toon_nose_lod0", ShaderABPath },
            { "Shader Forge/toon_textureanimation", ShaderABPath },
        };

        //Note: This will pull the shaders from the actual game files rather than the included shader AB, for the purpose of building the shader AB itself.
        //map.unity3d is from VKatsu at v_katsu\abdata\vtuber\map.unity3d. Copy it to the KK abdata folder before building.

        //internal static readonly Dictionary<string, string> ShaderABs = new Dictionary<string, string>
        //{
        //    { "Custom/CustomUnlit-Outline",  "map.unity3d" },
        //    { "Custom/Blend/Zero_Subtractive",  "map.unity3d" },
        //    { "Custom/Blend/Additive",  "map.unity3d" },
        //    { "Custom/Silhouette", "chara/oo_base.unity3d" },
        //    { "CustomUnlit/Transparent DoubleSide",  "map.unity3d" },
        //    { "Shader Forge/create_body", "chara/mm_base.unity3d" },
        //    { "Shader Forge/create_eye", "chara/mm_base.unity3d" },
        //    { "Shader Forge/create_eyewhite", "chara/mm_base.unity3d" },
        //    { "Shader Forge/create_hair", "chara/mm_base.unity3d" },
        //    { "Shader Forge/create_head", "chara/mm_base.unity3d" },
        //    { "Shader Forge/create_topN", "chara/mm_base.unity3d" },
        //    { "Shader Forge/main_alpha", "chara/co_bra_00.unity3d" },
        //    { "Shader Forge/main_color", "chara/ao_head_00.unity3d" },
        //    { "Shader Forge/main_emblem", "chara/co_top_00.unity3d" },
        //    { "Shader Forge/main_emblem_clothes", "chara/co_bra_00.unity3d" },
        //    { "Shader Forge/main_hair", "chara/bo_hair_b_00.unity3d" },
        //    { "Shader Forge/main_hair_front", "chara/bo_hair_f_00.unity3d" },
        //    { "Shader Forge/main_hair_low", "chara/bo_hair_b_00.unity3d" },
        //    { "Shader Forge/main_item", "chara/ao_arm_00.unity3d" },
        //    { "Shader Forge/main_item_ditherd", "chara/ao_head_09.unity3d" },
        //    { "Shader Forge/main_item_emission", "chara/ao_head_08.unity3d" },
        //    { "Shader Forge/main_item_low", "chara/bo_hair_b_00.unity3d" },
        //    { "Shader Forge/main_item_studio", "studio/mat/00.unity3d" },
        //    { "Shader Forge/main_item_studio_add", "studio/mat/00.unity3d" },
        //    { "Shader Forge/main_item_studio_alpha", "studio/mat/00.unity3d" },
        //    { "Shader Forge/main_opaque", "chara/co_bra_00.unity3d" },
        //    { "Shader Forge/main_opaque2", "chara/co_bra_10.unity3d" },
        //    { "Shader Forge/main_skin", "chara/mm_base.unity3d" },
        //    { "Shader Forge/main_skin_low", "chara/mm_base.unity3d" },
        //    { "Shader Forge/main_StandardMDK_studio", "studio/mat/00.unity3d" },
        //    { "Shader Forge/main_opaque_low", "chara/co_bra_00.unity3d" },
        //    { "Shader Forge/main_opaque_low2", "chara/co_bra_10.unity3d" },
        //    { "Shader Forge/main_texture", "chara/ao_hair_00.unity3d" },
        //    { "Shader Forge/main_texture_studio", "studio/mat/00.unity3d" },
        //    { "Shader Forge/mnpb", "chara/oo_base.unity3d" },
        //    { "Shader Forge/shadowcast", "chara/oo_base.unity3d" },
        //    { "Shader Forge/toon_eye_lod0", "chara/bo_head_00.unity3d" },
        //    { "Shader Forge/toon_eyew_lod0", "chara/bo_head_00.unity3d" },
        //    { "Shader Forge/toon_glasses_lod0", "chara/bo_head_00.unity3d" },
        //    { "Shader Forge/toon_nose_lod0", "chara/bo_head_00.unity3d" },
        //    { "Shader Forge/toon_textureanimation", "chara/mm_base.unity3d" },
        //};
    }

    public enum CategoryNo
    {
        //cha_sample_f,
        //cha_sample_m,
        //cha_eyeset,
        bodypaint_layout = 3,
        //cha_default_cos_f,
        //cha_default_cos_m,
        //cha_sample_voice = 6,
        facepaint_layout = 7,
        mole_layout,
        //cha_sample_m_ex,
        bo_head = 100,
        bo_hair_b,
        bo_hair_f,
        bo_hair_s,
        bo_hair_o,
        co_top,
        co_bot,
        co_bra,
        co_shorts,
        co_gloves,
        co_panst,
        co_socks,
        co_shoes,
        ao_none = 120,
        ao_hair,
        ao_head,
        ao_face,
        ao_neck,
        ao_body,
        ao_waist,
        ao_leg,
        ao_arm,
        ao_hand,
        ao_kokan,
        cpo_sailor_a = 200,
        cpo_sailor_b,
        cpo_sailor_c,
        cpo_jacket_a = 210,
        cpo_jacket_b,
        cpo_jacket_c,
        mt_face_detail = 400,
        mt_eyeshadow,
        mt_cheek,
        mt_lip,
        mt_lipline,
        mt_face_paint,
        mt_eyebrow,
        mt_eye_white,
        mt_eye,
        mt_eye_gradation,
        mt_eye_hi_up,
        mt_eye_hi_down,
        mt_eyeline_up,
        mt_eyeline_down,
        mt_nose,
        mt_mole,
        face_preset,
        mt_body_detail = 420,
        mt_body_paint,
        mt_sunburn,
        mt_nip,
        mt_underhair,
        mt_pattern = 430,
        mt_emblem,
        mt_ramp,
        mt_hairgloss,
        //ex_bo_body = 500,
        //ex_bo_head,
        //ex_bo_hair,
        //ex_co_clothes,
        //ex_co_shoes
    }

    public enum KeyType
    {
        Category,
        DistributionNo,
        AngleSpeed,
        CheekTex,
        ColorMask02AB,
        ColorMask02Tex,
        ColorMaskAB,
        ColorMaskTex,
        Coordinate,
        EpsTex,
        EpsTexAB,
        EyeBase,
        EyebrowTex,
        EyeHiDownTex,
        EyeHitomi,
        EyeHiUpTex,
        EyelineDownTex,
        EyelineShadowTex,
        EyelineUpTex,
        EyeObjNo,
        EyeshadowTex,
        EyesPtn,
        EyeTex,
        EyeWhiteTex,
        HideHair,
        ID,
        Kind,
        LineMask,
        LiplineTex,
        LipTex,
        MainAB,
        MainData,
        MainManifest,
        MainTex,
        MainTex02,
        MainTex02AB,
        MainTexAB,
        MatAB,
        MatData,
        MatManifest,
        MoleTex,
        Name,
        NipTex,
        NormalData,
        NormallMapDetail,
        NoseTex,
        NotBra,
        OverBodyMask,
        OverBodyMaskAB,
        OverBraMask,
        OverBraMaskAB,
        OverInnerMask,
        OverInnerMaskAB,
        PaintTex,
        Parent,
        Possess,
        SetHair,
        Sex,
        ShapeAnime,
        SizeSpeed,
        SizeWidth,
        StateType,
        SunburnTex,
        TileAnim,
        UnderhairTex,
        Yurayura,
        KokanHide,
        ThumbAB,
        ThumbTex,
        PosX,
        PosY,
        Rot,
        Scale,
        CenterX,
        MoveX,
        CenterY,
        MoveY,
        CenterScale,
        AddScale,
        DefCoorde01,
        DefCoorde02,
        DefCoorde03,
        DefCoorde04,
        DefCoorde05,
        DefCoorde06,
        DefCoorde07,
        Data01,
        Data02,
        Data03,
        Eyebrow01,
        Eyebrow02,
        Eyebrow03,
        Eye01,
        Eye02,
        Eye03,
        Mouth01,
        Mouth02,
        Mouth03,
        EyeHiLight01,
        EyeHiLight02,
        EyeHiLight03,
        ColorMask03AB,
        ColorMask03Tex,
        MainTex03AB,
        MainTex03,
        MabUV,
        HideShorts
    }
}
